---
- hosts: all
  sudo: yes
  vars:
    pxc_release: http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
    pxc_version: 5.5
  tasks:
    - include: tasks/system.yml
    - include: tasks/pxc_setup.yml
